name: Continuous Improvement

on:
  push:
    branches:
      - "**"
    paths:
      - "src/**"
      - ".github/workflows/ci.yaml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "src/**"

jobs:
  flask-app:
    runs-on: ubuntu-18.04

    env:
      MYSQL_ROOT_PASSWORD: XspE27F6veLzSBGk
      MYSQL_DATABASE: jumpcloud
      MYSQL_USER: jumpcloud
      MYSQL_PASSWORD: PHbnDDB8yFnvCQVK
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: jumpcloud
      DB_USER: jumpcloud
      DB_PASS: PHbnDDB8yFnvCQVK

    services:
      mysql:
        image: mysql:5.7.32
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 50

    steps:
      - uses: actions/checkout@v2

      - name: Use Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          python src/app.py &
          pytest src/tests/test_routes.py
